#pragma once

#include "bo3_package.h"

#include <QMap>

namespace bo3
{

enum class PackageTarget
{
    PostFx,
    Material,
    Skybox
};

enum class AutomationConfidence
{
    Auto,
    Guided,
    Unsupported
};

enum class TechsetOrigin
{
    None,
    Authored,
    AutoGenerated,
    Imported
};

enum class PackageResourceRole
{
    Unknown,
    ResolvedScene,
    FloatDepth,
    MaterialImage,
    Color,
    Normal,
    Opacity,
    Emissive,
    Mask,
    CubeMap,
    Ignore
};

struct SourceResource
{
    QString name;
    CompiledResourceKind kind = CompiledResourceKind::Unknown;
    TextureDimension dimension = TextureDimension::Unknown;
    int bindPoint = -1;
};

struct SourceConstant
{
    QString name;
    QString hlslType;
    QString defaultValue;
};

struct ShaderSourceAnalysis
{
    QString source;
    QVector<SourceResource> textures;
    QVector<SourceResource> samplers;
    QVector<SourceConstant> constants;
    QString pixelEntry = "ps_main";
    QString vertexEntry = "vs_main";
    QString pixelInputType;
    QString positionField;
    QString texcoordField;
    QString directionField;
    QString directionType;
    bool hasPixelEntry = false;
    bool hasVertexEntry = false;
    bool hasBo3FullscreenVertex = false;
    bool hasPostFxInclude = false;
    bool hasDirectionalInput = false;
    bool fullscreenInputIsAdaptable = false;
};

struct PackageResourceMapping
{
    QString resourceName;
    CompiledResourceKind resourceKind = CompiledResourceKind::Unknown;
    PackageResourceRole role = PackageResourceRole::Unknown;
    AutomationConfidence confidence = AutomationConfidence::Guided;
    QString selectedBinding;
    QStringList choices;
    QString reason;
};

struct PackageAdapterRequest
{
    PackageTarget target = PackageTarget::PostFx;
    PackageConfiguration configuration = PackageConfiguration::Runtime;
    QString source;
    QString sourceFileName;
    QMap<QString, QString> mappingOverrides;
};

struct PackageAdapterResult
{
    PackageTarget target = PackageTarget::PostFx;
    AutomationConfidence confidence = AutomationConfidence::Unsupported;
    QString adaptedSource;
    QString sourceFileName;
    TechsetModel techset;
    QVector<PackageResourceMapping> mappings;
    ValidationResult diagnostics;
    QString interfaceFingerprint;
    QString selectedTechnique = "lit";
    bool adaptedSourceRequired = false;
    bool generatedVertexStage = false;
};

struct AutoTechsetMetadata
{
    TechsetOrigin origin = TechsetOrigin::None;
    PackageTarget target = PackageTarget::PostFx;
    QString interfaceFingerprint;
    bool valid = false;
};

ShaderSourceAnalysis analyzeShaderSource(const QString& source);
QString shaderInterfaceFingerprint(const ShaderSourceAnalysis& analysis, PackageTarget target);
PackageAdapterResult adaptShaderPackage(const PackageAdapterRequest& request);

void appendAutoConstantParameters(
    TechsetModel& techset,
    const ShaderSourceAnalysis& analysis,
    const QString& tweakCategory,
    const QMap<QString, QString>& storageOverrides = {});

QString serializeAutoTechset(const PackageAdapterResult& result);
AutoTechsetMetadata readAutoTechsetMetadata(const QString& techsetSource,
                                            bool explicitlyImported = false);
bool isAutoTechsetStale(const QString& techsetSource, const QString& currentFingerprint);

QString toString(PackageTarget target);
QString toString(AutomationConfidence confidence);
QString toString(TechsetOrigin origin);
QString toString(PackageResourceRole role);

// Same-basename association is deliberately stateless: callers clear their
// active association before applying this result, preventing package reuse when
// switching shaders.
QString adjacentTechsetPath(const QString& shaderPath);

PackageAdapterResult adaptPostFxPackage(const PackageAdapterRequest& request,
                                        const ShaderSourceAnalysis& analysis);
PackageAdapterResult adaptMaterialPackage(const PackageAdapterRequest& request,
                                          const ShaderSourceAnalysis& analysis);
PackageAdapterResult adaptSkyPackage(const PackageAdapterRequest& request,
                                     const ShaderSourceAnalysis& analysis);

} // namespace bo3
